#!/bin/sh

if [ "$(git remote 2>/dev/null)" != "" ]; then
    target_tracking_branch="origin/$(git rev-parse --abbrev-ref HEAD)"
    for tracking_branch in $(git branch -ar) ; do
        if [ "$target_tracking_branch" = "$tracking_branch" ]; then
            echo "true"
        fi
    done
fi
